import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { QuestionnaireState } from './questionnaireSchema';

/**
 * Generates a branded PDF compliance plan.
 * @param plan The markdown content of the plan
 * @param userDetails The user's questionnaire answers
 * @returns Promise<Blob> The PDF file as a Blob
 */
export async function generatePDF(plan: string, userDetails: QuestionnaireState): Promise<Blob> {
  const doc = new jsPDF();

  // --- Branding & Header ---
  const primaryColor = '#2563eb'; // Blue
  
  // Header Bar
  doc.setFillColor(primaryColor);
  doc.rect(0, 0, 210, 40, 'F'); 
  
  // Logo Text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("ComplianceAlpha", 14, 20);
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Indian Freelancer Tax Compliance Roadmap", 14, 28);

  doc.setTextColor(0, 0, 0); // Reset text color

  // --- User Profile Summary ---
  let currentY = 50;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("User Profile Summary", 14, currentY);
  currentY += 5;

  const profileData = [
    ["Entity Type", userDetails.entity_type.replace(/_/g, ' ').toUpperCase()],
    ["Profession", userDetails.profession],
    ["Revenue", userDetails.revenue.replace(/_/g, ' ').toUpperCase()],
    ["Client Locations", userDetails.client_location.join(', ').toUpperCase()],
    ["Payment Methods", userDetails.payment_methods.join(', ').toUpperCase()],
    ["GST Number", userDetails.gst_number.toUpperCase()],
    ["LUT Filed", userDetails.lut_filed ? userDetails.lut_filed.replace(/_/g, ' ').toUpperCase() : 'N/A'],
    ["Tax Forms", userDetails.tax_forms.replace(/_/g, ' ').toUpperCase()],
    ["Capex", userDetails.capital_expenditure.replace(/_/g, ' ').toUpperCase()],
    ["Investments", userDetails.investments.replace(/_/g, ' ').toUpperCase()],
    ["Hiring", userDetails.hire_freelancers.toUpperCase()],
  ];

  autoTable(doc, {
    startY: currentY,
    head: [['Parameter', 'Value']],
    body: profileData,
    theme: 'striped',
    headStyles: { fillColor: primaryColor },
    margin: { top: 10 },
  });

  // @ts-ignore
  currentY = doc.lastAutoTable.finalY + 15;

  // --- AI Generated Plan Content ---
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(primaryColor);
  doc.text("Your Personalized Compliance Plan", 14, currentY);
  currentY += 10;
  
  doc.setTextColor(0, 0, 0);

  // Basic Markdown Parser for PDF
  const lines = plan.split('\n');
  const pageHeight = doc.internal.pageSize.height;
  const margin = 14;
  const maxLineWidth = 180;

  for (let i = 0; i < lines.length; i++) {
    let line = lines[i].trim();
    if (!line) continue;

    // Check for page break
    if (currentY > pageHeight - 20) {
      doc.addPage();
      currentY = 20;
    }

    if (line.startsWith('## ')) {
      // Section Header
      const text = line.replace('## ', '');
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0, 0, 0);
      currentY += 5; // Extra spacing before header
      doc.text(text, margin, currentY);
      currentY += 7;
    } else if (line.startsWith('### ')) {
      // Sub-header
      const text = line.replace('### ', '');
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(50, 50, 50);
      doc.text(text, margin, currentY);
      currentY += 6;
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      // Bullet Point
      const text = line.replace(/^[-*] /, '');
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(0, 0, 0);
      
      // Bullet character
      doc.text("•", margin, currentY);
      
      // Wrapped text
      const splitText = doc.splitTextToSize(text, maxLineWidth - 5);
      doc.text(splitText, margin + 5, currentY);
      currentY += (splitText.length * 5) + 2;
    } else {
      // Normal Paragraph
      // Strip Bold/Italic markers for cleaner PDF text
      const cleanText = line.replace(/\*\*/g, '').replace(/__/g, '');
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(0, 0, 0);
      
      const splitText = doc.splitTextToSize(cleanText, maxLineWidth);
      doc.text(splitText, margin, currentY);
      currentY += (splitText.length * 5) + 2;
    }
  }

  // --- Footer ---
  const pageCount = doc.getNumberOfPages();
  doc.setFontSize(8);
  doc.setTextColor(150);
  
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const footerText = "Generated by ComplianceAlpha. Not professional advice.";
    doc.text(footerText, 14, pageHeight - 10);
    doc.text(`Page ${i} of ${pageCount}`, 190, pageHeight - 10, { align: 'right' });
  }

  return doc.output('blob');
}
